ever-app:
  name: ticket

server:
  port: 8080
  servlet:
    context-path: /${ever-app.name}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  web:
    resources:
      add-mappings: false
  application:
    name: ${ever-app.name}
  datasource:
    url: jdbc:mariadb://localhost:3306/ticket?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select 1
    username: root
    password: 1234 #1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        storage_engine: innodb
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: true

kafka:
  topic_prefix: local
  url: localhost:9092